name = "svelte-cloudflare-firebase"
account_id = "204a36f7fd327a8afc7502d491a34f52"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true